package br.upf.ccc.notas.front;

import br.upf.ccc.appnotas.domain.Avaliacao;
import java.util.List;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class TelaNotas extends javax.swing.JFrame {
    List<Avaliacao> lista = new ArrayList<>();
    
    public TelaNotas() {
        try {
            initComponents();
            
            lista.add(new Avaliacao("A", 7f, 1f, null));
            lista.add(new Avaliacao("B", 5f, 3f, null));
            lista.add(new Avaliacao("C", 3f, 10f, null));
            lista.add(new Avaliacao("D", 7f, 8f, null));
            
            
            
            buttonListarActionPerformed(null);
        } catch (Exception ex) {
            Logger.getLogger(TelaNotas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNota1 = new javax.swing.JTextField();
        textNota2 = new javax.swing.JTextField();
        buttonIncluir = new javax.swing.JButton();
        buttonAlterar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        buttonListar = new javax.swing.JButton();
        buttonIncluirConstrutor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDados = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        textLog = new javax.swing.JTextArea();
        textLocalizar = new javax.swing.JTextField();
        buttonLocalizar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nome");

        textNome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nota 1");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nota 2");

        textNota1.setBackground(new java.awt.Color(255, 255, 255));

        textNota2.setBackground(new java.awt.Color(255, 255, 255));

        buttonIncluir.setBackground(new java.awt.Color(255, 255, 255));
        buttonIncluir.setForeground(new java.awt.Color(0, 0, 0));
        buttonIncluir.setText("Incluir");
        buttonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIncluirActionPerformed(evt);
            }
        });

        buttonAlterar.setBackground(new java.awt.Color(255, 255, 255));
        buttonAlterar.setForeground(new java.awt.Color(0, 0, 0));
        buttonAlterar.setText("Alterar");
        buttonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarActionPerformed(evt);
            }
        });

        buttonExcluir.setBackground(new java.awt.Color(255, 255, 255));
        buttonExcluir.setForeground(new java.awt.Color(0, 0, 0));
        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        buttonListar.setBackground(new java.awt.Color(255, 255, 255));
        buttonListar.setForeground(new java.awt.Color(0, 0, 0));
        buttonListar.setText("Listar");
        buttonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListarActionPerformed(evt);
            }
        });

        buttonIncluirConstrutor.setBackground(new java.awt.Color(255, 255, 255));
        buttonIncluirConstrutor.setForeground(new java.awt.Color(0, 0, 0));
        buttonIncluirConstrutor.setText("IncluirConstrutor");
        buttonIncluirConstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIncluirConstrutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(buttonIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonIncluirConstrutor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(textNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonIncluir)
                    .addComponent(buttonAlterar)
                    .addComponent(buttonExcluir)
                    .addComponent(buttonListar)
                    .addComponent(buttonIncluirConstrutor))
                .addContainerGap())
        );

        tableDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDados);

        textLog.setColumns(20);
        textLog.setRows(5);
        jScrollPane2.setViewportView(textLog);

        buttonLocalizar.setText("Localizar");
        buttonLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLocalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLocalizar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLocalizar))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIncluirActionPerformed
         try {
            // Instancionar objeto de avaliacao
            Avaliacao avl = new Avaliacao();
            
            // Inicializar os dados com o informado no form
            avl.setNome(textNome.getText());
            avl.setNota1(Float.valueOf(textNota1.getText()));
            avl.setNota2(Float.valueOf(textNota2.getText()));
            
            // Guardar o objeto numa lista em memoria
            lista.add(avl);
            
            //Atualizar a lista
            buttonListarActionPerformed(evt);
            
            //Adicionar log
            textLog.append("Incluido " + avl+"\n");
            
            limparCampos();
        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_buttonIncluirActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        // Pegar a linha selecionada
        int i = tableDados.getSelectedRow();
        
        // Remover o objeto da linha selecionada
        lista.remove(i);
        
        // Listar novamente = atualiza a tabela
        buttonListarActionPerformed(evt);
        
        limparCampos();
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void buttonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListarActionPerformed
        Object [][] matriz = new Object[lista.size()] [5];
        
        int i = 0;
        
        for(Avaliacao avl : lista){
            matriz[i][0] = avl.getNome();
            matriz[i][1] = avl.getNota1();
            matriz[i][2] = avl.getNota2();
            matriz[i][3] = avl.calcularMedia();
            matriz[i][4] = avl.situacao();
            i++;
         }
       
       tableDados.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Nome", "Nota 1", "Nota 2", "Media", "Situacao"
            }
        ));
    }//GEN-LAST:event_buttonListarActionPerformed

    private void buttonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarActionPerformed
        try {
            // Pegar a linha selecionada
            int i = tableDados.getSelectedRow();
            
            // Pegar o objeto da lista pela linha
            Avaliacao avl = lista.get(i);
            
            // Colocar os dados da tela no objeto = alterando
            avl.setNome(textNome.getText());
            avl.setNota1(Float.valueOf(textNota1.getText()));
            avl.setNota2(Float.valueOf(textNota2.getText()));
            
            // Listar lista novamente
            buttonListarActionPerformed(evt);
        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_buttonAlterarActionPerformed

    private void tableDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDadosMouseClicked
       // Identificar a linha selecionada
       int linha = tableDados.getSelectedRow();

       // Pegar da lista objeto respectivo a linha
        Avaliacao selecionado = lista.get(linha);
        
       // Colocar os dados do objeto nos componentes de for
       textNome.setText(selecionado.getNome());
       textNota1.setText(selecionado.getNota1().toString());
       textNota2.setText(selecionado.getNota2().toString());
    }//GEN-LAST:event_tableDadosMouseClicked

    private void buttonIncluirConstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIncluirConstrutorActionPerformed
        try {
            // Instanciar objeto e inicializar pelo construtor
            Avaliacao avl = new Avaliacao(
                    textNome.getText(),
                    Float.valueOf(textNota1.getText()),
                    Float.valueOf(textNota2.getText()),
                    null);
            
            //Armazenar o objeto na lista
            lista.add(avl);
            
            //Adicionar log 
            textLog.append("Incluido " + avl+"\n");
            
            buttonListarActionPerformed(evt);
            
            limparCampos();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_buttonIncluirConstrutorActionPerformed

    private void buttonLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLocalizarActionPerformed
        try {
            // Teste 1 = comparar se dois objetos são iguais
            Avaliacao a = new Avaliacao("A", 7f, 1f, null);
            Avaliacao b = new Avaliacao("A", 7f, 1f, null);

            if (a == b) {
                textLog.append("A e B são iguais");
            } else {
                textLog.append("A e B são diferentes\n");
            }

            textLog.append("Agora usando equals!\n");
            
            if (a.equals(b)) {
                textLog.append("A e B são iguais\n");
            } else {
                textLog.append("A e B são diferentes\n");
            }
            
            // --------------------------------------------------------
            Avaliacao loc =  new Avaliacao(textLocalizar.getText(), 0f, 0f, null);
            
            if(lista.contains(loc)){
                textLog.append("Encontrou na lista\n");
                textLog.append("NA posicao: " + lista.indexOf(loc) + "\n");
            } else{
                textLog.append("Não encontrou na lista\n");

            }

        } catch (Exception ex) {
            Logger.getLogger(TelaNotas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonLocalizarActionPerformed

     private void limparCampos() {
        textNome.setText("");
        textNota1.setText("");
        textNota2.setText("");
    }
     
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNotas().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAlterar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonIncluir;
    private javax.swing.JButton buttonIncluirConstrutor;
    private javax.swing.JButton buttonListar;
    private javax.swing.JButton buttonLocalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tableDados;
    private javax.swing.JTextField textLocalizar;
    private javax.swing.JTextArea textLog;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textNota1;
    private javax.swing.JTextField textNota2;
    // End of variables declaration//GEN-END:variables

}